### ISSUE TITLE
development setup?

### ISSUE THREAD

**Issue by runofthemill** [hakkens/davehakkens#15]
hi Dave - I'd love to help, but not sure how you have everything set up. are all the files in this repo found in wp-content/themes? just want to figure out how to set up my local WP instance so that it mimics the live site as closely as possible.

thanks!

**Comment by leo** [comment]
@runofthemill You need to place this repository within `wp-content/themes`, yep. :blush: But sadly, we have't yet found a way to make the data public, so you'll probably have to use sample data...

**Comment by runofthemill** [comment]
thanks @leo - otherwise is it a pretty standard WP install? is it running 4.4.2? any plugins I need to be aware of? cheers!

**Comment by leo** [comment]
@runofthemill I've just talked with @davehakkens about this. It looks like it sadly won't really work if you want to use it in your own setup (since it's too much custom data). But we're working on a solution for this for our next set of sites!

**Comment by runofthemill** [comment]
noted - that's too bad!

for the future solution - you could create a git for the whole wp-content folder, and use a plugin like [https://github.com/wp-sync-db/wp-sync-db](WP Sync DB) to provide a dump of the WP tables to the appropriate people. I've done it before and it's not too complicated :)

**Comment by leo** [comment]
@runofthemill Yep, we've already thought about that. However, it's very hacky and therefore not something we'll consider. Git isn't made for temporary files and sharing our DB will probably also generate more pain than success, since it contains more than 30.000 users and hundreds of other contents. Even just replacing the original URL with your development URL will take your editor of choice many many hours (millions of lines of code within the dump).

Nevertheless thank you for your effort in thinking about a great solution! :blush:

**Comment by runofthemill** [comment]
@leo no problem!

fyi, with the WP Sync DB plugin (which I just fixed the link for in my previous post) you can select which tables to dump, so you could exclude users and whatnot :P 

> Even just replacing the original URL with your development URL will take your editor of choice many many hours (millions of lines of code within the dump).

[this](https://interconnectit.com/products/search-and-replace-for-wordpress-databases/) is an excellent tool to deal with changing URLs from production/staging/development etc. takes a minute or two.

I've used the process I outlined here in production environments, and it's relatively straightforward. obviously I get the reluctance to hacky solutions, but it's not nearly as hacky as it appears. go with whatever solution makes the most sense to you, just wanted to share my two cents =D

**Comment by runofthemill** [comment]
hey @leo @davehakkens - one other tool that might make collaborative development on the various sites easier in the future

https://roots.io/bedrock-vs-regular-wordpress-install/

cheers!

**Comment by leo** [comment]
@runofthemill Thank you very much for your effort.

However, we're not planning to use WordPress anywhere in the future anymore. While [Precious Plastic](https://github.com/hakkens/precious-plastic) and [Story Hopper](https://github.com/hakkens/story-hopper) are already static sites generated using [Jekyll](https://jekyllrb.com) and hosted on GitHub Pages (we'll implement the same for [Phonebloks](https://phonebloks.com)), I'm also currently in the process of developing my own system that takes care of these things: [Muffin](http://muffin.cafe) ([code](https://github.com/muffinjs/app)).

While I was a big fan of WP in the beginning, it's simply not keeping up to the current web standards and web tooling. Because of that, we've decided to drop it in the future!

**Comment by runofthemill** [comment]
Very cool! I'll check Muffin out :) Are you planning on having that serve as a replacement for the forums as well? Or using something like [Discourse](https://www.discourse.org/) for that functionality?

**Comment by leo** [comment]
Since the site is pretty new, it will probably take a long time until we rebuild it again. But if we do it, yes: Discourse would be my favourite (since it's built with Ember, like Muffin).
