### ISSUE TITLE
Avatar size wrong

### ISSUE THREAD

**Issue by Jerzeek** [hakkens/davehakkens#30]
![profilepic](https://user-images.githubusercontent.com/22919620/27997717-c30cb146-64fe-11e7-9a37-f876975d3941.png)

**Comment by davehakkens** [comment]
Caching?


On 9 July 2017 at 23:32:10, Jerzeek (notifications@github.com) wrote:

[image: profilepic]
<https://user-images.githubusercontent.com/22919620/27997717-c30cb146-64fe-11e7-9a37-f876975d3941.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hakkens/davehakkens/issues/30>, or mute the thread

**Comment by Jerzeek** [comment]
yes......
