### ISSUE TITLE
Map/forum API?

### ISSUE THREAD

**Issue by Jerzeek** [hakkens/davehakkens#34]
He Guys :)

Since we are launching the map I would like to stay updated to new pins.
The idea is to have a buzzer going of whenever a new pin is added

I have been doing some work with ESP8266's/ESP32's and I was wondering if it's possible to get this .json format that shows how many pins there are currently are.
and maybe later also get update's if there are new forum topics

Would be awesome :D

**Comment by nzchicken** [comment]
Buzzers FTW.

The map front end currently just makes a call to a wordpress rest api which returns a JSON array of results. In theory it's accessible from anywhere, so you should just be able to use this to plug into what you're trying to do:

https://davehakkens.nl/wp-json/map/v1/pins

Have a look and let me know whether you need any more information. Some fields you might be interested in are created_date, modified_date which aren't currently in the response, but can be added pretty easily.

As for the forum post part, would need to have a look at how we'd accomplish this. I know the above works because that part I built :-)

**Comment by Jerzeek** [comment]
😍 This was what i was looking for,
i can acces it so should be good :)
Let's first make this work, then we can look at the forum ;)
will keep you updated!
