### ISSUE TITLE
Add messages counter to avatar on header

### ISSUE THREAD

**Issue by kooler62** [hakkens/davehakkens#63]
![afd55b5bff](https://user-images.githubusercontent.com/5638391/33096386-792c685c-cf0f-11e7-9104-f28d740c0567.png)

**Comment by davehakkens** [comment]
I agree. would love that


On 21 November 2017 at 21:59:35, kooler62 (notifications@github.com) wrote:

[image: afd55b5bff]
<https://user-images.githubusercontent.com/5638391/33096386-792c685c-cf0f-11e7-9104-f28d740c0567.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hakkens/davehakkens/issues/63>, or mute the thread

**Comment by davehakkens** [comment]
added in the next update :)
