### ISSUE TITLE
fix balances changes when avatar upload again

### ISSUE THREAD

**Issue by kooler62** [hakkens/davehakkens#64]
I uploaded the same photo several times in a row. And every time I got a charge on my balance. I think it needs to be fixed. Any user can significantly raise their balance in a few minutes. I think it's worth it to raise the balance only for the first photo upload.

**Comment by davehakkens** [comment]
Thanks. fixed now. Also deducted you 1600 points, sorry mate 😅


On 21 November 2017 at 22:12:18, kooler62 (notifications@github.com) wrote:

I uploaded the same photo several times in a row. And every time I got a
charge on my balance. I think it needs to be fixed. Any user can
significantly raise their balance in a few minutes. I think it's worth it
to raise the balance only for the first photo upload.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hakkens/davehakkens/issues/64>, or mute the thread
