### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by kooler62** [hakkens/davehakkens#66]
Members, who "Most likes given last month" have the same links like https://davehakkens.nl/community/dashboard/# 
Must be like https://davehakkens.nl/community/members/NAME
![22-11-2017 22-33-46](https://user-images.githubusercontent.com/5638391/33148863-21ba22b8-cfd6-11e7-91f0-14bba631c8ad.png)

**Comment by davehakkens** [comment]
Wel spotted
Are you by any chance good in coding or have friends that can help out? :)


On 22 November 2017 at 21:40:40, kooler62 (notifications@github.com) wrote:

Members, who "Most likes given last month" have the same links like
https://davehakkens.nl/community/dashboard/#
[image: 22-11-2017 22-33-46]
<https://user-images.githubusercontent.com/5638391/33148863-21ba22b8-cfd6-11e7-91f0-14bba631c8ad.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hakkens/davehakkens/issues/66>, or mute the thread

**Comment by davehakkens** [comment]
fixed in 2.3 🔥
